### ISSUE TITLE
Dusts are not smelting

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#10]
Metal dusts retrieved from sieving dust (hammer sand to dust) are not able to be smelted in the new version 0.7.12. They can't be used for anything, they can't be crafted into a block of dust, no crafting recipe in NEI nor they are accepted by the furnace or the smeltery.

Posted these bugs as well on the comment page, but figured to make an account on GIT to notify you easier.

**Comment by Drakma** [comment]
Dusts work a little bit differently now with the new Ex Nihilo Adscenscio.  That being said I don't like the way it works and am fixing it.

**Comment by AstroxV** [comment]
I tried everything i could with the dusts i received from sieving dust, but nothing works. So maybe i'm missing something and it's not a bug. I didn't mind the way sieves changed, but if they give items that can't be used for anything (like the metal dusts, unless i'm missing something) it's a bit weird.

**Comment by Drakma** [comment]
the dusts are by default only allowed to be smelted in a vanilla furnace.

All 3 of the pieces of each ore received via sieving is now available to smelt in a tinkers' smeltery (for double ore) or smelted in a furnace (for one ingot)

will be available in next update (probably late tonight after my stream is done).
