### ISSUE TITLE
Mouse scroll action used by 2 mods at once

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#11]
Mouse tweaks interferes with another mod, causing when moving items to the inventory with the scroll wheel, they wont move. One mod is set to add items with scroll up, and one mod is set to remove items witch scroll up for example. Disabling mouse tweaks' scroll tweak will fix it. I can't find which other mod uses the scroll wheel to move items between inventories.

version 0.7.12

**Comment by Drakma** [comment]
Hrm. I see the issue now.  I'll keep taking a look.

**Comment by AstroxV** [comment]
I saw you changed it in the latest version 0.7.33. It's moving 2 items at the time now tho, but at least its usable.
As you left this issue open i'm guessing you're still looking into it. Out of interest, do you know which other mod other than mouse tweaks is offering the scroll functionality? Since I found many modpacks which have the same issue.

**Comment by Drakma** [comment]
Fixed in latest build
