### ISSUE TITLE
Ghast tear diamand mesh chance low

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#13]
To receive a ghast tear from sifting soul sand gives a 7% chance on an iron mesh, and 1% on diamond mesh. This is on both a normal sieve or a heavy sieve. I'm new to how the new sieving system works, but this percentage looks off as the chance of drops only increases for everything else the better quality mesh you use.

**Comment by Drakma** [comment]
Drops changed in latest release

**Comment by AstroxV** [comment]
I saw you changed this in the latest version 0.7.38 of the pack, but the percentages are still the same ingame.

**Comment by Drakma** [comment]
I see 1,3,5,8% in the downloaded config.

**Comment by AstroxV** [comment]
I did a fresh install. This is what i see ingame: http://i68.tinypic.com/mmwiti.png
version 0.7.38

You just updated, let me check again...

**Comment by Drakma** [comment]
It's highly possible I forgot to click "save" before I packaged the new version up.

**Comment by AstroxV** [comment]
Yup, checked, its fixed in the latest version, thank you
