### ISSUE TITLE
Rubber seeds missing

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#14]
Just as i'm checking up on a bug you update the pack, sorry for all the reports and not being faster :(
There seems there is no way to get rubber now in the pack. Before you could get rubber seeds from sieving, but they disappeared, the whole item is missing now.

PS: Enjoying the pack allot! Thanks for it!

**Comment by Drakma** [comment]
Added rubber saplings into dirt sieving.  Thanks for the bug testing!

**Comment by AstroxV** [comment]
The texture is broken in the sieve results of the rubber sappling i noticed. I didnt check percentages or anything, my minecraft needs like 10 minutes or more to get the pack running between each check :(

**Comment by AstroxV** [comment]
The percentages seem off, its for string, flint, iron, diamond: 1, 20, 3 and 40
