### ISSUE TITLE
Sieve percentage emeralds iron mesh

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#15]
Flint mesh has a chance of gettin emeralds out of gravel for 0.7%.
The iron mesh only has 0.1% chance.
String mesh has 0.3% chance so think the iron mesh percentage is wrong.

**Comment by Drakma** [comment]
Fixed  in latest

**Comment by AstroxV** [comment]
Emeralds now have 0.3% for silk, 0.7% for flint, 1% for iron and 1% for diamond meshes. If the last two are intended to be the same percentage its no problem. Just with how everything goes up in chance with the higher meshes it could be a mistake, so throwing it out there anyway.

**Comment by Drakma** [comment]
Diamond is actually higher, it's just a display error
On Dec 11, 2016, at 7:16 AM, AstroxV <notifications@github.com<mailto:notifications@github.com>> wrote:

Emeralds now have 0.3% for silk, 0.7% for flint, 1% for iron and 1% for diamond meshes. If the last two are intended to be the same percentage its no problem. Just with how everything goes up in chance with the higher meshes it could be a mistake, so throwing it out there anyway.
