### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#16]
The following textures are missing:
Milk (inside bucket/items/machines)
Blood tank (can't be crafted i think, so might not be a problem)
Chaos Crystal (same as above)
Rubber Sapling (inside sieve results)

**Comment by Drakma** [comment]
rubber sapling fixed
not worried about blood tank or chaos crystal as they are not implemented
can't replicate milk but I'll keep this open

**Comment by AstroxV** [comment]
Holding a bucket of milk in my hand shows a pink/black texture inside the bucket.
I'll do a fresh reinstall in the morning to check if its not something wrong in my game.

**Comment by Drakma** [comment]
Happy to say these are finally fixed!
