### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by kulflame** [Drakma/VacantSky#19]
One of the players was creating lava using a cobble gen > hopper>crucible. Server shows no crash and works fine, this crash only applies to clients.  Maybe it's a rendering issue?  Not sure... going ot try and re-create this single player.

 Crashes anyone online (with or without optifine) here is my crash log. 
http://pastebin.com/7cJhk7ec

**Comment by Drakma** [comment]
Looks like a rendering issue.  I'll pass along to dev.
On Dec 11, 2016, at 2:41 PM, Kulflame <notifications@github.com<mailto:notifications@github.com>> wrote:

One of the players was creating lava using a cobble gen > hopper>crucible. Crashes anyone online. here is my crash log. Server shows no crash and works fine, this crash only applies to clients. Maybe it's a rendering issue? Not sure... going ot try and re-create this single player.

http://pastebin.com/7cJhk7ec

**Comment by kulflame** [comment]
Recreated it in single player.  Place a Wooden Barrel.  Shift click a hopper on top of it and BOOM crash.

**Comment by Drakma** [comment]
Insaneau was aware and the fix is done in the latest.  Just waiting on Curse to update.
