### ISSUE TITLE
Inferior Inferium Crop recipe

### ISSUE THREAD

**Issue by kulflame** [Drakma/VacantSky#2]
Inferior Inferium Crop recipe in JEI says to put 6 Inferium Essence into the Petal Apothecary from Botania to create the plant...  but the Petal Apothecary does not accept the Essences.  

Please advise if this is a config error with Botania or if it is a JEI recipe error (in this case would the only way to farm the Essences be via a mob farm?)

**Comment by Drakma** [comment]
This was unintended.  None of the recipes I made seem to be working.  I'll keep looking at it.

**Comment by Drakma** [comment]
Something has happened with modtweaker or botania since I originally made these recipes.  I will talk to the mod dev.

Until then, I have changed the recipes to just using mana infusion.
