### ISSUE TITLE
Angel Ring recipe doesn't work.

### ISSUE THREAD

**Issue by kulflame** [Drakma/VacantSky#22]
Checked all items id's and they are all matching to recipe.  When you put the items in manually or place from JEI it will not create the angel ring.

**Comment by Drakma** [comment]
that's a JEI issue with not showing the correct NBT data.  

I'll post the actual recipe as soon as I am done with my current project.

**Comment by Drakma** [comment]
From top left to bottom right:

Pixie in a SoulVial, Iridium Nugget, Lasso'd Wither
Iridium Nugget, Obsidian Skull Ring, Iridium Nugget
Lasso'd Bat, Iridium Nugget, Lasso'd Ghast

The Angel Ring is the end game ring and the JetPacks will have increased power consumption to compensate
