### ISSUE TITLE
Manually breeding chickens gives black eggs

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#23]
When breeding chickens from the Chickens-mod witch eachother by feeding seeds will result in eggs having black textures.
When chickens breed through a nesting pen of the Hatchery mod, the eggs have the right textures.

**Comment by Drakma** [comment]
I believe this is a known issue, but I will double check when I get home
On Dec 12, 2016, at 5:47 AM, AstroxV <notifications@github.com<mailto:notifications@github.com>> wrote:

When breeding chickens from the Chickens-mod witch eachother by feeding seeds will result in eggs having black textures.
When chickens breed through a nesting pen of the Hatchery mod, the eggs have the right textures.

**Comment by Drakma** [comment]
This is how it is supposed to be.  Use hatchery for more predictability
