### ISSUE TITLE
Building wands crash

### ISSUE THREAD

**Issue by spinshock** [Drakma/VacantSky#24]
[crash-2016-12-16_17.35.26-client.txt](https://github.com/Drakma/VacantSky/files/657595/crash-2016-12-16_17.35.26-client.txt)

Everytime I look at a cobblestone generator tier 1 with a building wand in my hand the blocks that are rendered cause the instance to crash with this crash-report log.

**Comment by Drakma** [comment]
Appears to be a known issue.  I'll leave this open until it's fixed.

**Comment by Drakma** [comment]
Should be fixed in latest
