### ISSUE TITLE
Mods not needed on server?

### ISSUE THREAD

**Issue by tjsd** [Drakma/VacantSky#25]
Hello!
I tried running a server of this, but it crashes with SoundFilters-0.9_for_1.9.4.
I suspect that might be a clientside only mod, so I disabled it on the server.
But whenever I try to connect I get fatal error, missing blocks.

Also I wonder what type of world I should set it to in the serverproperties.

**Comment by kulflame** [comment]
Yes take SoundFilters mod out for server.  
level-type=DEFAULT

That's literally all you have to do.  I used the startup files and libraries from All the Sky to do my server and just deleted the mods, scripts and configs and pasted in Vacant ones.

No problem after that.

**Comment by kulflame** [comment]
If you want I can dropbox my server files or you could join us :)

**Comment by Drakma** [comment]
Take out SoundFilters and add/edit "level-type=botania-skyblock" in server.properties and you're ready to go

**Comment by tjsd** [comment]
I would say these mods are also client only.
CustomMainMenu-MC1.10.2-2.0.2.jar
MenuMobs-1.10.2-1.14.jar
MouseTweaks-2.6.4-mc1.10.2.jar

But even with a brand new world created with botania-skyblock I get the same message. I even transfered the mods, scripts and config folders again.
This is the output from my client log:
http://pastebin.ubuntu.com/23642097/

seems there is somethingwrong with mystical agriculture and ae2

I run 2 other servers fine for different packs, but I just cant get this one to work.

@kulflame hit me up on discord or something, im sverd there
