### ISSUE TITLE
Osmium

### ISSUE THREAD

**Issue by kulflame** [Drakma/VacantSky#26]
I may have overlooked this in JEI but I don't see an option to get osmium anymore.

**Comment by Drakma** [comment]
I just checked.  There is not.  I will add to dust tables in next update.

**Comment by AstroxV** [comment]
Osmium can still be gotten from the Orechid of Botania, converting stone to ores.
~~Also the void miner of Environmental Tech gives osmium.~~

**Comment by kulflame** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } That isn't the intended progression for osmium though.  He added it back to the dusts.


Sent from Yahoo Mail for iPhone


On Wednesday, December 21, 2016, 9:11 PM, AstroxV <notifications@github.com> wrote:


Osmium can still be gotten from the Orechid of Botania, converting stone to ores.

**Comment by spinshock** [comment]
I made rftools dimension and mined some osmium ore to get the mystical agriculture osmium seeds. You can get osmium trough Rockhound:Chemistry as well.

**Comment by AstroxV** [comment]
Could you guide me a little in the direction how to start with Rockhound? I can't find any tutorials of this mod, all I can find out is how to make Salt, but not what to do with it.

**Comment by Drakma** [comment]
Added to sieves.

**Comment by AstroxV** [comment]
This change didn't get through? It's not in the sieves in the latest version as far as i can see.

**Comment by Drakma** [comment]
It was misspelled.  Latest release has the change

On Dec 28, 2016, at 9:37 AM, AstroxV <notifications@github.com<mailto:notifications@github.com>> wrote:

This change didn't get through? It's not in the sieves in the latest version as far as i can see.
