### ISSUE TITLE
Lootbags can contain untextured tconstruct items

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#28]
Lootbags (legendary, epic and uncommon) can contain some untextured tinkers construct items.

**Comment by Drakma** [comment]
They're just default now.  I will be changing the loot table completely soon
On Dec 17, 2016, at 3:54 PM, AstroxV <notifications@github.com<mailto:notifications@github.com>> wrote:

Lootbags (legendary, epic and uncommon) can contain some untextured tinkers construct items.

**Comment by Drakma** [comment]
items removed in latest build
