### ISSUE TITLE
Dark Soularium Jetplate no recipe

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#29]
The Dark Soularium Jetplate of Simple Jetpacks 2 has no crafting recipe. When looking it up in JEI it says it requires itself to craft it, and only shows the upgraded version. Also the Dark Soularium Thruster has no known recipe for what it is used in, as I assume it is used to create the jetplate.

**Comment by Drakma** [comment]
There was an update to simply jet packs that added that in.  I'm still unsure how I want to handle it so I left it un-craftable for the moment.
On Dec 18, 2016, at 9:26 AM, AstroxV <notifications@github.com<mailto:notifications@github.com>> wrote:

The Dark Soularium Jetplate of Simple Jetpacks 2 has no crafting recipe. When looking it up in JEI it says it requires itself to craft it, and only shows the upgraded version. Also the Dark Soularium Thruster has no known recipe for what it is used in, as I assume it is used to create the jetplate.

**Comment by AstroxV** [comment]
No worries, just getting so many resources I'm just looking for stuff to craft :p
