### ISSUE TITLE
Mekanism JEI and WAILA issues

### ISSUE THREAD

**Issue by kulflame** [Drakma/VacantSky#3]
When looking at the Metallurgic Infuser it shows as an Enrichment Chamber.  

Also when you look up recipes for the Mekanism machines... say you look up Metallurgic Infuser in JEI... it shows you recipes for 7 machines.

  FYI.

**Comment by kulflame** [comment]
Also the lunchbox and lunch bag textures from Pam's are broken.  A huge magenta box :(

**Comment by Drakma** [comment]
That may be the resource pack.  I'll take a look tomorrow after work.

On Nov 9, 2016, at 8:38 PM, kulflame <notifications@github.com<mailto:notifications@github.com>> wrote:

Also the lunchbox texture is hella wrong. A huge magenta box :(

**Comment by Drakma** [comment]
Yeah it does that for me in other packs as well.  I'll take a deeper look but I am fairly certain that is a JEI bug.

On Nov 9, 2016, at 8:26 PM, kulflame <notifications@github.com<mailto:notifications@github.com>> wrote:

When looking at the Metallurgic Infuser it shows as an Enrichment Chamber.

Also when you look up recipes for the Mekanism machines... say you look up Metallurgic Infuser in JEI... it shows you recipes for 7 machines.

FYI.

**Comment by kulflame** [comment]
WAILA also does that with Extra Utilities Manual Mill (Says Solar Panel).

**Comment by Drakma** [comment]
So the Mekanism issue appears to be something inherent with Mekanism as all version of the 1.10.2 version do this.  I will pass along to the mod author
