### ISSUE TITLE
Torcherino too overpowered?

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#30]
I'm not sure, but I just found the torcherino... don't you think that item is a bit too overpowered compared to what it needs to be crafted? Maybe that's the whole idea of this pack, but there are so many items already to speed up crop growth. I didn't know about this item until now and it would have made things way too easy if I would have used it from the moment I could have.
I know noone is telling me to use it, and I won't :) But maybe this item should need a much harder recipe or is not needed at all :)

Just my little feedback about this item :D

**Comment by Drakma** [comment]
This has been on my list since I launched this pack.  I made it a little more difficult to craft, but I still think it's OP.  I've tried to get in contact with the mod author but s/he has yet to respond

**Comment by Drakma** [comment]
I'm a little more comfortable with the recipe of this now.
