### ISSUE TITLE
Unable to craft floating flowers (Botania)

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#33]
The recipe for floating flowers require 2 tin cans of forestry, but when trying to craft it it's not working. When i try to add the recipe from JEI to the crafting grid, it tells me the tin cans are missing from my inventory. I assume they have to be filled with something which JEI is not showing, but I don't know what.

**Comment by Drakma** [comment]
You are correct.  Jei is not showing the helium in the cans.


On Dec 22, 2016, at 3:07 AM, AstroxV <notifications@github.com<mailto:notifications@github.com>> wrote:

The recipe for floating flowers require 2 tin cans of forestry, but when trying to craft it it's not working. When i try to add the recipe from JEI to the crafting grid, it tells me the tin cans are missing from my inventory. I assume they have to be filled with something which JEI is not showing, but I don't know what.

**Comment by AstroxV** [comment]
Helium is not working. But after some searching I found out a can filled with Vapor of Levity does work...
To create Vapor of Levity you need to grind a crystal with a Shulker soul... That seems a bit too challenging to me for a few floating flowers :p

**Comment by Drakma** [comment]
I have a change coming get that'll be easier.

On Dec 22, 2016, at 6:51 AM, AstroxV <notifications@github.com<mailto:notifications@github.com>> wrote:

Helium is not working. But after some searching I found out a can filled with Vapor of Levity does work...
To create Vapor of Levity you need to grind something a Shulker drops... That seems a bit too challenging to me for a few floating flowers :p

**Comment by Drakma** [comment]
You now create floating flowers by right clicking a barrel of helium with a glimmering flower
