### ISSUE TITLE
Rockhound: Chemistry ores?

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#35]
Is there any way to get the uninspected minerals in a skymap? The void miner is not getting the materials needed. I never used this mod and wanted to give it a try. But the only way I see I might be able to get the minerals is by using the quantum quarry as it seems like that will use normal oregen for its materials. Unfortunately that needs me to get to the end, and I didn't do that yet. But is that the way to go?
I don't think you can do anything with that mod without the minerals.

**Comment by Drakma** [comment]
I will probably remove this mod unless people want them.  You should be able to get all ores via the quantum quarry

**Comment by Drakma** [comment]
I'm keeping the mods in.  All ores can be obtained via quantum quarry

**Comment by AstroxV** [comment]
I have a Quantum Quarry running for a few days but I haven't found any Uninspected Minerals. I don't know if I'm doing something wrong, or how to get started at all with this mod. As far as I understand you need to mine Uninspected Minerals. Can it be that these Minerals are not found by my Quarry since I started playing before this mod was added?
