### ISSUE TITLE
Uncraftable Ender Chest

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#36]
The vanilla Ender Chest is not craftable but is needed in a few recipes.

**Comment by Drakma** [comment]
On my to do list

Sorry.  Christmas hours are catching up with me.  I'll get these done soon.

On Dec 23, 2016, at 3:13 PM, AstroxV <notifications@github.com<mailto:notifications@github.com>> wrote:

The vanilla Ender Chest is not craftable but is needed in a few recipes.

**Comment by AstroxV** [comment]
No worries, have a good xmas :)

**Comment by Drakma** [comment]
Removed
