### ISSUE TITLE
Vivid grass spawns rather useless flowers

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#37]
I think this is something you added manually to the pack. When you place a barrel of water on Vivid Grass it will turn into Helium. It also spawns Botania flowers around the barrel in the same way as mushrooms spawn around Witch Water barrels.
I'm not sure if it's a mistake or not, but the flowers that spawn are Shiny Flowers which are only used for making floating islands. It kinda makes sense as I think the Helium created this way you want to use as well for floating flowers (#33). But still wana check that was your intend or not.

**Comment by Drakma** [comment]
Fixed in latest Build
