### ISSUE TITLE
Unable to get Chorus Fruit

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#38]
I killed the Ender Dragon a couple of times now and went through the portals to the Outer Islands where normally you can find Chorus Fruit plants, but so far I haven't found any. Is Chorus fruit supposed to spawn on the tiny island you end up on after going through the portal with the ender pearl?
I also visited a bunch of End Cities and Ships and didn't find any.
Maybe I'm missing something where to find them? Or are they nowhere to be found?

**Comment by Drakma** [comment]
They are sievable in the new version
