### ISSUE TITLE
Wither boss spawn.

### ISSUE THREAD

**Issue by spinshock** [Drakma/VacantSky#40]
I can't seem to find a way to spawn the wither as i am placing soul sand and wither skulls. I even tried placing the block formation flat on the ground. If it was changed in this modpack, can someone tell me how to spawn it. ty in advance

**Comment by AstroxV** [comment]
The usual way of 4 Soulsand in a T shape standing up and then place the Wither Skeleton Skulls on top of it. Make sure you place the heads last.

**Comment by spinshock** [comment]
http://prntscr.com/dnz6oh
http://prntscr.com/dnz6v0
It's not spawning i even let the formation like that while i was sleeping last night.

**Comment by AstroxV** [comment]
Weird... And you placed the heads last? Wither spawns instantly here once I place the last head.

**Comment by spinshock** [comment]
yes i placed soul sand first and wither skulls last one by one left to right if it matters. no luck i will try in a new world.

**Comment by AstroxV** [comment]
Are you in peaceful mode?

**Comment by spinshock** [comment]
Im an idiot dont mind me you can close the issue.
