### ISSUE TITLE
Sag Mill unlimited ore.

### ISSUE THREAD

**Issue by spinshock** [Drakma/VacantSky#41]
If you sag mill the ore chunks from gravel you get ore dust. That is okay, you can make dark steel balls to get 50% doubling chance, w/e. The problem comes when you can still sag mill the ore dust its self making more ore dust. If you are crushing the ore dust without flint or dark steel balls you are just getting 1:1 crushing but when you use flint or dark steel balls you are able to duplicate said ore dust and if its intended its too op.

**Comment by Drakma** [comment]
Fixed in latest build.  You can still do it, but it will cost you a huge amount of RF
