### ISSUE TITLE
Applied energistics power

### ISSUE THREAD

**Issue by spinshock** [Drakma/VacantSky#42]
Applied energistics's energy acceptor is not receiving from any source of power. 
I tried Flux Networks's Flux Plug, Ultimate Universal Mekanism Cables, ExU2 Generators directly placed next to it.
The only way to power it is trough enderio power cables and the vibration chamber(AE2).

**Comment by Drakma** [comment]
I am using EnderIO power just fine. 

Universal Cables won't work as it is a known bug

I'm not sure what Flux Plug is

ExtraUtils2 generators used fine for me.

Have you modified that pack?

**Comment by spinshock** [comment]
I did change 1 or 2 config files and nothing related to power or AE2 or Mekanism. Flux plug is from flux networks which is wireless power. For me eXu2 gens dont work with ae2 power.

**Comment by Drakma** [comment]
I don't have Flux Networks in the pack.

On Dec 27, 2016, at 5:00 PM, spinshock <notifications@github.com<mailto:notifications@github.com>> wrote:

I did change 1 or 2 config files and nothing related to power or AE2 or Mekanism. Flux plug is from flux networks which is wireless power. For me eXu2 gens dont work with ae2 power.

**Comment by Drakma** [comment]
Haven't heard any other issues so closing
