### ISSUE TITLE
Wings of the Bats make Angel Ring unneeded

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#47]
The Wings of the Bat (Actually Additions) is not too hard to make (only requires to get to the Ender Dragon) and lets the user fly the same as the angel ring does. Only in the 1.11 version of Actually Additions the wings are limited to 40 seconds flight, but in our version its unlimited.

**Comment by Drakma** [comment]
I had just assumed.  I'll refactor the recipe

**Comment by Drakma** [comment]
Changed! I'm happy with this result.
