### ISSUE TITLE
Sand wont go into SAG Mill

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#48]
Before sand in the SAG Mill would give sSilicon. With the latest update that's not working anymore. Dono if it's a bug or I should change my production line.

**Comment by Drakma** [comment]
Bug.  Fixed in new version.
On Dec 30, 2016, at 4:30 PM, AstroxV <notifications@github.com<mailto:notifications@github.com>> wrote:

Before sand in the SAG Mill would give sSilicon. With the latest update that's not working anymore. Dono if it's a bug or I should change my production line.

**Comment by Drakma** [comment]
Fixed in latest
