### ISSUE TITLE
Chaos Guardian keeps despawning

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#50]
I killed the chaos guardian once, but now every time i get to a chaos island, I see the healthbar of the guardian, but if I move out of range of the guardian so the bar disappears, the guardian is gone.
It won't spawn again, and the chaos chrystal inside the island is invulnerable.
Also when I start to shoot at the crystals in the towers, the whole towers get destroyed like happens after defeating the guardian.

**Comment by Drakma** [comment]
Known issue https://github.com/brandon3055/Draconic-Evolution/issues/484

**Comment by Drakma** [comment]
According to brandon this will never be fixed but I'll still keep an eye on it.
