### ISSUE TITLE
Nowhere to find uninspected mineral of rockhounding mod

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#51]
I tried everything to find the uninspected minerals of the rockhounding mod but no success.
I tried the ender quarry, the void miner, making a RF dimension, the deep dark, but nowhere I can find that material to get started with this mod. I don't know if i'm mining at the wrong level, or if the miners don't have the material whitelisted to mine it, but nothing to be found.
The config for rochhounding shows the material should spawn in the Aroma dimension, but that mod is not installed so we don't have that dimension I think.
What am I missing or doing wrong?

**Comment by Drakma** [comment]
you're doing nothing wrong.  I'm still working on integrating the entire mod.

**Comment by Drakma** [comment]
It can now be found from the void ore miner
