### ISSUE TITLE
Sieve gives disabled items

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#52]
When sieving dust and endstone with a diamond mesh there is one item that says it's disabled from Applied Energetics (4448:46), and one untextured item of TechReborn (9254:60).

I'm not sure which item it was that's disabled and if it affects me. I noticed I have it in a drawer stored, but can't figure out what it was before.

**Comment by Drakma** [comment]
Item numbers can change, what was the name of the items?

**Comment by AstroxV** [comment]
The one thats invisible is called "This item is disabled" (appliedenergistics2:material) and the other untextured "item.techreborn.dustsmall.PLACEHOLDER_ITEM.name" (techreborn:smallDust).

**Comment by Drakma** [comment]
Fixed in latest
