### ISSUE TITLE
Sieve gives too many items for a single block

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#53]
The Sieve gives too many items per sieved item it seems. I use a Diamond Stiffened Mesh which is enchanted with fortune 3 and each piece of dust gives 10 different dusts. The same with sieving gravel.
One piece results in 7 to 10 results.

A normal diamond mesh (unenchanted) gives 1 to 5 results out of a single block sieved.

**Comment by Drakma** [comment]
Such is the "OP"ness of meshes.  I'll start a new world and check progression

**Comment by AstroxV** [comment]
I was talking about the auto sieve, sorry.
They never were that OP. Before I used food on them to speed the progress up. If I do that now they overflow with stuff.

**Comment by Drakma** [comment]
Hrm.  The autosieve should pull the same things as the standard sieve.  I can't specify something "just" for autosieves

**Comment by AstroxV** [comment]
Oh, I didn't test if it is the same in the regular sieve. I assumed its the same for them. I can test it later. I just forgot to specify in my initial post that I noticed this behavior for the auto-sieve. Didn't mean it's explicit for the auto-sieve, only noticed it on them.

**Comment by Drakma** [comment]
Ah gotcha.  I'm still a bit behind on this pack, sorry.  IRL got a hold of me.  I'm doing what I can in my spare time!  Thanks for all the bug reports!

**Comment by Drakma** [comment]
Ok, so they are acting appropriately.  The Diamond meshes are max tier, "hard" to craft.  So they are end game sieving.  The fortune just makes it insane.
