### ISSUE TITLE
Conversion issue Yellorium/Uranium

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#54]
When combining 9 yellorium you get a uranium block or if you use the switch button for oredictionary a yellorium block. The ME crafting can not switch to an alternate result and makes a uranium block (uranium blocks are not allowed in a big-reactors reactor).
A uranium block can be crafted to 9 uranium and a yellorium block can be crafted into 9 yellorium ingots.
But there is no way to turn a uranium block back into yellorium. 

Maybe you can add an alternate result for a uranium block to give 9 yellorium so we can convert them back.
Or better change the recipe of uranium and yellorium to craft yellorium ingots into uranium ingots somehow and not through the block form.

Found out that a compacting drawer can craft a block of uranium down into uranium ingots, which is not possible through normal crafting as it would give uranium (not ingots). And it crafts yellorium ingots down to uranium nuggets, which is also not possible through normal crafting as it should become yellorium nuggets. But at least those 2 bugged conversions allow me to convert blocks of uranium back to blocks of yellorium. By breaking the blocks of uranium down to uranium nuggets, and use those in a compacting drawer to convert them to yellorium blocks.

**Comment by Drakma** [comment]
I'll add a recipe to convert them back and forth.


On Jan 18, 2017, at 9:31 AM, AstroxV <notifications@github.com<mailto:notifications@github.com>> wrote:

When combining 9 yellorium you get a uranium block or if you use the switch button for oredictionary a yellorium block. The ME crafting can not switch to an alternate result and makes a uranium block (uranium blocks are not allowed in a big-reactors reactor).
A uranium block can be crafted to 9 uranium and a yellorium block can be crafted into 9 yellorium ingots.
But there is no way to turn a uranium block back into yellorium.

Maybe you can add an alternate result for a uranium block to give 9 yellorium so we can convert them back.
Or better change the recipe of uranium and yellorium to craft yellorium ingots into uranium ingots somehow and not through the block form.

Found out that a compacting drawer can craft a block of uranium down into uranium ingots, which is not possible through normal crafting as it would give uranium (not ingots). And it crafts yellorium ingots down to uranium nuggets, which is also not possible through normal crafting as it should become yellorium nuggets. But at least those 2 bugged conversions allow me to convert blocks of uranium back to blocks of yellorium. By breaking the blocks of uranium down to uranium nuggets, and use those in a compacting drawer to convert them to yellorium blocks.

**Comment by Drakma** [comment]
Added in latest
