### ISSUE TITLE
Immesive Engineering breaks DE recepe's in JEI

### ISSUE THREAD

**Issue by AstroxV** [Drakma/VacantSky#55]
There is a problem with the latest version of IE (0.10-55) causing it to break the display of fusion crafting recipes for DE.
I ran into this problem myself on my own custom pack. Downgrading to IE 0.10-54 fixes the problem.
https://github.com/brandon3055/Draconic-Evolution/issues/550

**Comment by brandon3055** [comment]
Can confirm. This does not make any sense to me but i am looking into it.
I am currently debugging this issue in the FS3 pack and what i have found is rather confusing...
First of all if i just transfer the pack to MultiMC the issue goes away completely. 
When running the pack on the curse launcher this issue goes away if you remove ModTweaker.
When running on the legacy FTB launcher the only way to fix this is to remove IE (I suspect rolling it back a version would also fix it based on what i have read here.)

**Comment by Zarkov2** [comment]
This is listed as fixed in version 0.10-57 of Immersive Engineering, and I can confirm that version solved the problem for me.

**Comment by Drakma** [comment]
Updated in latest release.
