### ISSUE TITLE
RF Tools Crafters cannot accept recipes

### ISSUE THREAD

**Issue by kulflame** [Drakma/VacantSky#7]
When I first make these when we first played we had zero issues.  Now the crafters will not accept any recipes at all.  When you go to drop items in the grid on the top right nothing happens.  

Yes I double clicked the slot.

**Comment by Drakma** [comment]
Thanks, this was fairly easy to reproduce.  I'm looking at it now.

**Comment by Drakma** [comment]
Fixed in latest build.  Will be available later today.
