### ISSUE TITLE
Crash when entering game with new update

### ISSUE THREAD

**Issue by kulflame** [Drakma/VacantSky#9]
http://pastebin.com/5Qp4qxAM

**Comment by Drakma** [comment]
Are you able to create a new world and load it?
On Dec 8, 2016, at 6:29 AM, Kulflame <notifications@github.com<mailto:notifications@github.com>> wrote:

http://pastebin.com/5Qp4qxAM

**Comment by kulflame** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } It's obviously something in my world.  I can create a new world and load in.  I deleted my player data and inventory and such and still got the crash.  Would you think it's just baubles causing the crash?  


Sent from Yahoo Mail for iPhone


On Thursday, December 8, 2016, 7:21 AM, Drakma <notifications@github.com> wrote:

Are you able to create a new world and load it?
On Dec 8, 2016, at 6:29 AM, Kulflame <notifications@github.com<mailto:notifications@github.com>> wrote:

http://pastebin.com/5Qp4qxAM

**Comment by Drakma** [comment]
I can't duplicate, but I would  assume baubles or torcherino at this point.

**Comment by Drakma** [comment]
Update to the latest pack and try again.  I still can't get this to duplicate

**Comment by kulflame** [comment]
The new update fixes the crash.  Thank you!
